In [1]:
import nltk
import pandas as pd
import string

from nltk.chat.util import Chat,reflections

In [2]:
pairs=[
    ["(Hello, Ray)",["Hello, what's yout name?"]],
     ["My name is (.*)",["hi %1"]],
    ["(Are you a robot?)",["yes, I'm a digital assistant named Shane"]]
    
    
    
]

In [3]:
chat=Chat(pairs,reflections)

In [4]:
#chat.converse()

In [5]:
# Define the documents
doc_trump = "Mr. Trump became president after winning the political election. Though he lost the support of some republican friends, Trump is friends with President Putin"

doc_election = "President Trump says Putin had no political interference is the election outcome. He says it was a witchhunt by political parties. He claimed President Putin is a friend who had nothing to do with the election"

doc_putin = "Post elections, Vladimir Putin became President of Russia. President Putin had served as the Prime Minister earlier in his political career"

documents = [doc_trump, doc_election, doc_putin]

In [6]:
# Scikit Learn
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Create the Document Term Matrix
count_vectorizer = CountVectorizer(stop_words='english')
count_vectorizer = CountVectorizer()
sparse_matrix = count_vectorizer.fit_transform(documents)

# OPTIONAL: Convert Sparse Matrix to Pandas Dataframe if you want to see the word frequencies.
doc_term_matrix = sparse_matrix.todense()
df = pd.DataFrame(doc_term_matrix, 
                  columns=count_vectorizer.get_feature_names(), 
                  index=['doc_trump', 'doc_election', 'doc_putin'])
df

after  as  became  by  career  claimed  do  earlier  election  \
doc_trump         1   0       1   0       0        0   0        0         1   
doc_election      0   0       0   1       0        1   1        0         2   
doc_putin         0   1       1   0       1        0   0        1         0   

              elections  ...  the  though  to  trump  vladimir  was  who  \
doc_trump             0  ...    2       1   0      2         0    0    0   
doc_election          0  ...    2       0   1      1         0    1    1   
doc_putin             1  ...    1       0   0      0         1    0    0   

              winning  witchhunt  with  
doc_trump           1          0     1  
doc_election        0          1     1  
doc_putin           0          0     0  

[3 rows x 48 columns]

In [7]:
# Compute Cosine Similarity
from sklearn.metrics.pairwise import cosine_similarity
print(cosine_similarity(df, df))
#> [[ 1.          0.48927489  0.37139068]
#>  [ 0.48927489  1.          0.38829014]
#>  [ 0.37139068  0.38829014  1.        ]]

[[1.         0.51480485 0.38890873]
 [0.51480485 1.         0.38829014]
 [0.38890873 0.38829014 1.        ]]


In [9]:
# Define the documents
doc_soup = "Soup is a primarily liquid food, generally served warm or hot (but may be cool or cold), that is made by combining ingredients of meat or vegetables with stock, juice, water, or another liquid. "

doc_noodles = "Noodles are a staple food in many cultures. They are made from unleavened dough which is stretched, extruded, or rolled flat and cut into one of a variety of shapes."

doc_dosa = "Dosa is a type of pancake from the Indian subcontinent, made from a fermented batter. It is somewhat similar to a crepe in appearance. Its main ingredients are rice and black gram."

documents = [doc_trump, doc_election, doc_putin, doc_soup, doc_noodles, doc_dosa]

In [14]:
pip install -U gensim

  Found existing installation: Cython 0.29.12
    Uninstalling Cython-0.29.12:
      Successfully uninstalled Cython-0.29.12
Note: you may need to restart the kernel to use updated packages.


In [16]:
import gensim
# upgrade gensim if you can't import softcossim
#pip uninstall gensim
#pip install gensim
#pip install --upgrade gensim
from gensim.matutils import softcossim 
from gensim import corpora
import gensim.downloader as api
from gensim.utils import simple_preprocess
print(gensim.__version__)
#> '3.6.0'

# Download the FastText model
fasttext_model300 = api.load('fasttext-wiki-news-subwords-300')

3.8.3


In [11]:
# Prepare a dictionary and a corpus.
dictionary = corpora.Dictionary([simple_preprocess(doc) for doc in documents])

# Prepare the similarity matrix
similarity_matrix = fasttext_model300.similarity_matrix(dictionary, tfidf=None, threshold=0.0, exponent=2.0, nonzero_limit=100)

# Convert the sentences into bag-of-words vectors.
sent_1 = dictionary.doc2bow(simple_preprocess(doc_trump))
sent_2 = dictionary.doc2bow(simple_preprocess(doc_election))
sent_3 = dictionary.doc2bow(simple_preprocess(doc_putin))
sent_4 = dictionary.doc2bow(simple_preprocess(doc_soup))
sent_5 = dictionary.doc2bow(simple_preprocess(doc_noodles))
sent_6 = dictionary.doc2bow(simple_preprocess(doc_dosa))

sentences = [sent_1, sent_2, sent_3, sent_4, sent_5, sent_6]

NameError: name 'corpora' is not defined

In [17]:
# Compute soft cosine similarity
print(softcossim(sent_1, sent_2, similarity_matrix))
#> 0.567228632589

NameError: name 'sent_1' is not defined

In [ ]:
import numpy as np
import pandas as pd

def create_soft_cossim_matrix(sentences):
    len_array = np.arange(len(sentences))
    xx, yy = np.meshgrid(len_array, len_array)
    cossim_mat = pd.DataFrame([[round(softcossim(sentences[i],sentences[j], similarity_matrix) ,2) for i, j in zip(x,y)] for y, x in zip(xx, yy)])
    return cossim_mat

In [ ]:
soft_cosine_similarity_matrix(sentences)

In [2]:
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer

# chatbot = ChatBot('Ron Obvious')

# # Create a new trainer for the chatbot
# trainer = ChatterBotCorpusTrainer(chatbot)

# # Train the chatbot based on the english corpus
# trainer.train("chatterbot.corpus.english")

# # Get a response to an input statement
# chatbot.get_response("Hello, how are you today?")

ModuleNotFoundError: No module named 'chatterbot'

In [3]:
import chatterbot

ModuleNotFoundError: No module named 'chatterbot'